FC=gfortran
CXX=g++
FFLAGS = -g -O0 -fPIC -fallow-argument-mismatch -fsanitize=address
CXXFLAGS = -D COSMIC -D BSE_BASE -g -O0 -std=c++11 -fsanitize=address
FCLIBS = -lgfortran -lm -lasan
BSE_PATH=cosmic
LIB=libbse_asan.a
TEST=petar.cosmic_asan
SRC_F := $(shell find $(BSE_PATH) -name '*.f' ! -name '[sb]se.f' ! -name 'mo[sb]se.f' ! -name 'popbin.f')
OBJ_F := $(SRC_F:.f=.ao)

%.ao: %.f
	$(FC) $(FFLAGS) -c $< -o $@

$(LIB): $(OBJ_F)
	ar rcs $@ $^

$(TEST): bse_test.cxx $(LIB) bse_interface.h
	$(CXX) $(CXXFLAGS) $< -o $@ -L./ -lbse_asan $(FCLIBS)

clean:
	rm -f $(BSE_PATH)/*.ao $(BSE_PATH)/SSE/*.ao *.ao $(TEST) $(LIB)
